function [c, s] = problem415_infinite_series(x)
%PROBLEM415_INFINITE_SERIES Sum the Infinite Series
%
% Given that 0 < x and x < 2*pi where x is in radians, write a function
%   [c, s] = infinite_series(x);
% that returns with the sums of the two infinite series
%   c = cos(2*x)/1/2 + cos(3*x)/2/3 + cos(4*x)/3/4 + ... + cos((n+1)*x)/n/(n+1) + ...
%   s = sin(2*x)/1/2 + sin(3*x)/2/3 + sin(4*x)/3/4 + ... + sin((n+1)*x)/n/(n+1) + ...

% Closed forms found by using Wolfram alpha.
fc = @(x) -0.5 * exp(-i * x) * (-exp(2i * x) - exp(i * x) * ...
                 log(1 - exp(i * x)) + exp(2i * x) * log(1 - exp(i * x)) - ...
                 exp(i * x) * log(exp(-i * x) * (-1 + exp(i * x))) + ...
                 log(exp(-i * x) * (-1 + exp(i * x))) - 1);
fs = @(x) 0.5i * exp(-i * x) * (-1 + exp(i * x)) * ...
               (-exp(i * x) + exp(i * x) * log(1 - exp(i * x)) + ...
                 log(exp(-i * x) * (-1 + exp(i * x))) - 1)
c = real(fc(x));
s = real(fs(x));
end
